apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-slave
  labels:
    app: jenkins-slave
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-slave
  template:
    metadata:
      labels:
        app: jenkins-slave
    spec:
      containers:
      - name: jenkins-slave
        image: oneoneonepig/jk-slave:0.2
        env:
        - name: JENKINS_AUTH
          value: "admin:admin"
        - name: JENKINS_URL
          value: "http://jenkins-master:8080"
