apiVersion: v1
kind: Service
metadata:
  name: jenkins-master
  labels:
    app: jenkins-master
spec:
  selector:
    cicd-master: "true"
  ports:
  - name: http
    nodePort: 30000
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: slavelistener
    port: 50000
    protocol: TCP
    targetPort: 50000
  type: NodePort
  #---
#apiVersion: v1
#kind: Service
#metadata:
#  name: jenkins-master-jnlp
#  labels:
#    app: jenkins-master-jnlp
#spec:
#  selector:
#    cicd-master: "true"
#  ports:
#  - port: 50000
#    protocol: TCP
#    targetPort: 50000
#  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins-master
  labels:
    app: jenkins-master
    cicd-master: "true"
    cicd-agent: "true"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jenkins-master
      cicd-master: "true"
      cicd-agent: "true"
  template:
    metadata:
      labels:
        app: jenkins-master
        cicd-master: "true"
        cicd-agent: "true"
    spec:
      containers:
      - name: jenkins
        image: "jenkins/jenkins:lts"
